# Site settings
title: Personal Budget Study
email: joshmelville@gmail.com
baseurl: "/pbstudy" # the subpath of your site, e.g. /blog/
copyright: Copyright 2015.
url: "http://jthrilly.github.io" # the base hostname & protocol for your site
twitter_username: jthrilly
github_username:  jthrilly

# Build settings
markdown: kramdown
